# Generated by Django 2.2.11 on 2020-04-02 20:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('country', models.CharField(max_length=2)),
                ('birth_year', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('year_release', models.SmallIntegerField()),
                ('copies_in_stock', models.SmallIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='BookLease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_date', models.DateField(auto_now_add=True)),
                ('leaseover_date', models.DateField(default=datetime.datetime(2020, 4, 16, 20, 1, 45, 791800))),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='jlibrary.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('city', models.TextField()),
                ('country', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Buddy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('lease', models.ManyToManyField(through='jlibrary.BookLease', to='jlibrary.Book')),
            ],
        ),
        migrations.AddField(
            model_name='booklease',
            name='buddy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='jlibrary.Buddy'),
        ),
        migrations.CreateModel(
            name='BookCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jlibrary.Author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jlibrary.Book')),
                ('inspirer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspired_by', to='jlibrary.Author')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(through='jlibrary.BookCreator', to='jlibrary.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jlibrary.Publisher'),
        ),
    ]
