# Generated by Django 2.2.12 on 2020-04-20 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlibrary', '0003_auto_20200413_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklease',
            name='leaseover_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 3, 45, 41, 166916)),
        ),
    ]
