# Generated by Django 2.2.12 on 2020-04-20 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlibrary', '0004_auto_20200420_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklease',
            name='leaseover_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 4, 34, 14, 532714)),
        ),
    ]
