# Generated by Django 2.2.12 on 2020-04-29 17:04

from django.db import migrations, models
import jlibrary.models


class Migration(migrations.Migration):

    dependencies = [
        ('jlibrary', '0005_auto_20200420_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklease',
            name='leaseover_date',
            field=models.DateField(default=jlibrary.models.calculate_default_leasetime),
        ),
    ]
