# Generated by Django 2.2.12 on 2020-04-29 17:05

from django.db import migrations, models
import jlibrary.models


class Migration(migrations.Migration):

    dependencies = [
        ('jlibrary', '0006_auto_20200429_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, upload_to=jlibrary.models.upload_bookpic),
        ),
    ]
